services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_capstone
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio_capstone
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio123
  #   command: server /data --console-address ":9001"
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio_data:/data

  # redis:
  #   image: redis:8
  #   container_name: redis_capstone
  #   ports:
  #     - "6379:6379"
  #   restart: always

volumes:
  pgdata:
  # minio_data: